config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :posts do
    resources :comments
    resources :tags
  end
  resources :sessions
  resources :users
  root to: 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :tags
  has_many :comments
  validates :description, presence: true
  has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tags
  has_many :comments
  validates :email, presence: true
  validates_uniqueness_of :email

  def self.search(find)
    where("email like ?", "%#{find}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not Authorized" if current_user.nil?
  end

end

app/controllers/comment_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if comment.valid?
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
  end

private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.all
  end

  def create
    @user = User.where(:user_id => current_user.id)
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if @comment.valid?
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end

private
  def comment_params
    params.require(:comment).permit(:comment, :user_id).merge(:user_id => current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authorize, only:[:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.valid?
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @tags = @post.tags
    @comments = @post.comments
    @comment = Comment.new
    @tag = Tag.new
    render 'show'
  end

  private
  def post_params
    params.require(:post).permit(:image, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is incorrect"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

 before_filter :authorize, only:[:new, :create]

  def new
    @post = Post.find(params[:post_id])
    @tag = Tag.new
  end

  def create
    @post = Post.find(params[:post_id])
    @tag = @post.tags.create(tag_params)
    if @tag.valid?
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to post_path(@post)
  end

private
  def tag_params
    params.require(:tag).permit(:user_id, :post_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    if params[:search]
      # binding.pry
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up!"
      redirect_to root_path
    else
      render "new"
    end
  end


private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", posts_path %>
  <%= link_to "New Post", new_post_path %>
  <%= link_to "Search Users", users_path %>

  <% if current_user %>
  Logged in as <%= current_user.email %>
  <%= link_to "log Out", logout_path %>
  <% else %>
  <%= link_to "New User", signup_path %>
  <%= link_to "Log In", login_path %>
  <% end %>

  <%= flash[:notice] %>
  <%= flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :url => posts_path, :html => { :multipart => true } do |f| %>
  <%= f.label "Add Discription: " %>
  <%= f.text_field :description %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<br><br>
<% @posts.each do |post| %>
  <%= link_to image_tag(post.image.url(:medium)), post_path(post.id) %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<br><br>
<%= image_tag @post.image.url %>
<br>
<%= @post.description %>

<%= render 'tags/form' %>
<h4>Tags</h4>
<ul>
<% @post.tags.each do |tag| %>
  <li><%= tag.user.email %></li>
<% end %>
</ul>

<h4>Comments</h4>
<ul>
  <% @post.comments.each do |comment| %>
    <li><%= comment.comment %></li>
  <% end %>
</ul>
<%= render '/comments/form' %>

app/views/tags/_form.html.erb
<%= form_for [@post, @tag] do |f| %>
  <%= f.collection_select :user_id, User.all, :id, :email, {prompt: "Tag a User"} %>
  <%= f.submit %>
<% end %>

app/views/tags/new.html.erb
<h1>Tag It</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Search for Users</h1>


<%= form_tag(users_path, :method => 'get', id: "search-form") do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "search" %>
<% end %>

<ul>
<% @users.each do |user| %>
<li><%= link_to "#{user.email}", user_path(user.id) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'layouts/errors' %>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<ul>
<% @user.tags.each do |tag| %>
  <%= image_tag tag.post.image %>
<% end %>
</ul>